### ISSUE TITLE
Split json data

### ISSUE THREAD

**Issue by nogic1008** [ddradar/ddr-song-info#3]
`chart.json` is very large. (it has over 100000 lines)
So we need to split file by series. (ex. chart-a20.json)

## Tasks
- [x] Split json file by series
- [x] Move files to `data/charts/` and `data/songs/` folder
- [ ] Change node script to read multiple files
